# Generated by Django 4.2.16 on 2024-11-17 07:26

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('Name', models.CharField(max_length=10)),
                ('Accountno', models.IntegerField(primary_key=True, serialize=False)),
                ('DoB', models.DateField()),
                ('Annualincome', models.IntegerField()),
                ('Address', models.CharField(max_length=10)),
                ('Aadharno', models.IntegerField()),
            ],
        ),
    ]        