# Generated by Django 4.2.16 on 2024-11-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Accountno', models.IntegerField(primary_key=True, serialize=False)),
                ('Amountincome', models.FloatField()),
                ('Address', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Borrower',
        ),
    ]
